"""CVAT "Ultralytics YOLO Pose 1.0" export -> training-ready YOLO pose dataset.

Label line format (all positions normalized to 0-1 by image width/height):

    class  cx cy w h  x_cap y_cap v_cap  x_base y_base v_base      v: 2 visible, 1 occluded, 0 outside

Fixes applied to every line:
  1. Boxes. CVAT exports a skeleton's box as the tight box around its points; with only two
     points on a tube that is a line (often ~0 px wide or tall). The box is rebuilt around the
     labelled points (v > 0) padded by PAD_PX on all four sides -- the box is axis-aligned, so
     the tube's thin direction can be x, y or both depending on its angle. With only one
     labelled point the box is +-SINGLE_HALF_PX around it (tube direction unknown).
  2. Outside points (v = 0) keep stale coordinates in CVAT; they are written as 0 0 0.
"""

import random
import shutil
from pathlib import Path

import cv2
import pandas as pd
from PIL import Image

PAD_PX = 45           # ~half the cap diameter (~85 px in the crop)
SINGLE_HALF_PX = 75   # box half-size when only one point is labelled
KPT_NAMES = ["cap", "base"]
SPLIT_MAP = {"kp_train": "train", "kp_val": "val"}

# DATA LABEL FORMAT: class cx cy w h x_cap y_cap v_cap x_base y_base v_base

def parse_line(line: str) -> tuple[int, list[float], list[list[float]]]:
    vals = [float(v) for v in line.split()]
    if len(vals) != 11:
        raise ValueError(f"expected 11 fields (class, box, 2x kpt), got {len(vals)}: {line!r}")
    return int(vals[0]), vals[1:5], [vals[5:8], vals[8:11]]


def format_line(cls: int, box: list[float], kpts: list[list[float]]) -> str:
    parts = [str(cls)] + [f"{b:.6f}" for b in box]
    for x, y, v in kpts:
        parts += [f"{x:.6f}", f"{y:.6f}", str(int(v))]
    return " ".join(parts)


def fix_line(line: str, img_w: int, img_h: int) -> tuple[str | None, dict]:
    """Return (fixed line or None if nothing is labelled, info for the report)."""
    cls, box, kpts = parse_line(line)
    info = {"orig_w_px": box[2] * img_w, "orig_h_px": box[3] * img_h,
            "v_cap": int(kpts[0][2]), "v_base": int(kpts[1][2])}

    pts = [(x * img_w, y * img_h) for x, y, v in kpts if v > 0]
    info["n_labelled"] = len(pts)
    if not pts:
        return None, info

    pad = PAD_PX if len(pts) == 2 else SINGLE_HALF_PX
    xs, ys = [p[0] for p in pts], [p[1] for p in pts]
    x0, x1 = max(min(xs) - pad, 0.0), min(max(xs) + pad, float(img_w))
    y0, y1 = max(min(ys) - pad, 0.0), min(max(ys) + pad, float(img_h))
    new_box = [(x0 + x1) / 2 / img_w, (y0 + y1) / 2 / img_h, (x1 - x0) / img_w, (y1 - y0) / img_h]
    info["new_w_px"], info["new_h_px"] = x1 - x0, y1 - y0

    new_kpts = [[0.0, 0.0, 0] if v == 0 else [x, y, v] for x, y, v in kpts]
    return format_line(cls, new_box, new_kpts), info


def build_dataset(images_dir: Path, labels_dir: Path, manifest: pd.DataFrame, out_dir: Path) -> pd.DataFrame:
    """Copy images and write fixed labels into out_dir/{images,labels}/{train,val}. Returns a per-image report."""
    split_of = {row.file: SPLIT_MAP.get(row.split) for row in manifest.itertuples()}
    rows = []
    for img_path in sorted(images_dir.glob("*.jpg")):
        rec = {"file": img_path.name, "split": split_of.get(img_path.name)}
        label_path = labels_dir / f"{img_path.stem}.txt"
        if rec["split"] is None:
            rec["status"] = "not in manifest / not a kp split"
        elif not label_path.exists() or not label_path.read_text().strip():
            rec["status"] = "no label"
        else:
            img_w, img_h = Image.open(img_path).size
            lines, infos = [], []
            for line in label_path.read_text().strip().splitlines():
                fixed, info = fix_line(line, img_w, img_h)
                infos.append(info)
                if fixed:
                    lines.append(fixed)
            rec.update(infos[0])  # one tube per image; first line is enough for the report
            rec["n_lines"] = len(lines)
            if lines:
                for sub in ("images", "labels"):
                    (out_dir / sub / rec["split"]).mkdir(parents=True, exist_ok=True)
                shutil.copy2(img_path, out_dir / "images" / rec["split"] / img_path.name)
                (out_dir / "labels" / rec["split"] / label_path.name).write_text("\n".join(lines) + "\n")
                rec["status"] = "ok"
            else:
                rec["status"] = "nothing labelled"
        rows.append(rec)
    return pd.DataFrame(rows)


def write_dataset_yaml(out_dir: Path) -> Path:
    """Ultralytics dataset config. Absolute `path` because it is generated per machine (lives in data/, gitignored)."""
    path = out_dir / "dataset.yaml"
    path.write_text(
        "# Generated by scripts/03_build_yolo_dataset.py -- do not edit by hand.\n"
        f"path: {out_dir.resolve().as_posix()}\n"
        "train: images/train\n"
        "val: images/val\n"
        "kpt_shape: [2, 3]   # 2 keypoints: x, y, visibility\n"
        "flip_idx: [0, 1]    # flips never swap cap and base\n"
        "names:\n"
        "  0: tube\n"
        f"# keypoint order: {KPT_NAMES}\n"
    )
    return path


def draw_label(img, line: str):
    """Box (green), cap (red), base (blue). Filled circle = visible, ring = occluded, nothing = outside."""
    h, w = img.shape[:2]
    _, (cx, cy, bw, bh), kpts = parse_line(line)
    x0, y0 = int((cx - bw / 2) * w), int((cy - bh / 2) * h)
    x1, y1 = int((cx + bw / 2) * w), int((cy + bh / 2) * h)
    cv2.rectangle(img, (x0, y0), (x1, y1), (0, 200, 0), 2)
    for (x, y, v), color, name in zip(kpts, [(0, 0, 255), (255, 0, 0)], KPT_NAMES):
        if v == 0:
            continue
        p = (int(x * w), int(y * h))
        cv2.circle(img, p, 9, color, -1 if v == 2 else 3)
        cv2.putText(img, name, (p[0] + 12, p[1] - 12), cv2.FONT_HERSHEY_SIMPLEX, 0.8, color, 2)
    return img


def save_check_images(out_dir: Path, report: pd.DataFrame, check_dir: Path, n_random: int, seed: int = 0) -> list[str]:
    """Overlay fixed labels on a random sample plus the edge cases (thinnest original boxes, single-point frames)."""
    ok = report[report["status"] == "ok"].copy()
    ok["orig_min_px"] = ok[["orig_w_px", "orig_h_px"]].min(axis=1)
    picks = set(ok.nsmallest(5, "orig_min_px")["file"]) | set(ok[ok["n_labelled"] == 1]["file"])
    rest = sorted(set(ok["file"]) - picks)
    picks |= set(random.Random(seed).sample(rest, min(n_random, len(rest))))

    check_dir.mkdir(parents=True, exist_ok=True)
    split_of = dict(zip(ok["file"], ok["split"]))
    for name in sorted(picks):
        split = split_of[name]
        img = cv2.imread(str(out_dir / "images" / split / name))
        for line in (out_dir / "labels" / split / f"{Path(name).stem}.txt").read_text().splitlines():
            draw_label(img, line)
        cv2.imwrite(str(check_dir / name), img)
    return sorted(picks)
